### ISSUE TITLE
UAGithubReachabilityStatusDidChangeNotification is not defined

### ISSUE THREAD

**Issue by oscardelben** [owainhunt/UAGithubEngine#11]
Hi, I was trying to compile the example app, but it is complaining that UAGithubReachabilityStatusDidChangeNotification

Which is used here:

static void reachabilityCallback(SCNetworkReachabilityRef target, SCNetworkReachabilityFlags flags, void\* info)
{
    [[NSNotificationCenter defaultCenter] postNotificationName:UAGithubReachabilityStatusDidChangeNotification object:info];
}

I tried a search in project but I couldn't find it anywhere else.

**Comment by owainhunt** [comment]
Apologies, fixed in the latest commit.

**Comment by oscardelben** [comment]
Thanks, I'm currently using your library and hopefully I'll be able to make some contributions. Specifically I'm looking for grouping all the engine files in a subdirectory so that it's easy to use them in a different project, and changing the include <Cocoa/Cocoa.h> so that it works out of the box for both cocoa and ios.

**Comment by owainhunt** [comment]
I've considered moving to a fully-fledged framework/static library, but until then you can just drag the 'Engine' group from one project to another and it'll work as expected.
