### ISSUE TITLE
initWithUsername apiKey not implemented

### ISSUE THREAD

**Issue by oscardelben** [owainhunt/UAGithubEngine#12]
Hi, in the Readme code you show how to initialize a GithubEngine:

UAGithubEngine *engine = [[UAGithubEngine alloc] initWithUsername:@"aUser" apiKey:@"aKey" delegate:self];

However that method is not implemented, and one has to provide their password instead.

**Comment by owainhunt** [comment]
Authentication with API key is now deprecated in favour of the HTTP authentication now used in UAGE. I'll update the README to reflect the change.
