### ISSUE TITLE
Are you planning on adding any orgs api calls to this?

### ISSUE THREAD

**Issue by balanon** [owainhunt/UAGithubEngine#17]
Are you still working on improving this? Are you planning on adding any orgs api calls to this? Are you planning on doing more API v3 work?

**Comment by owainhunt** [comment]
I'm definitely planning to work more on this. It's the basis of IssuesHub so as that app develops, so does the engine behind it. I've been working away for the last couple of months, but as soon as I'm back home, work will resume!

Feel free to fork and add in the meantime ;)

**Comment by balanon** [comment]
cool :)
