### ISSUE TITLE
Invalid Login in credentials seem to cause a crash

### ISSUE THREAD

**Issue by dominickm** [owainhunt/UAGithubEngine#24]
Owain, 

I have noticed that if you use the engine with invalid credentials, it crashes. This seems to be related to the error pointer. I'm looking into a work around.

**Comment by owainhunt** [comment]
Is this using the most recently committed code? I did make some changes to the error handling in the last commit.

**Comment by dominickm** [comment]
Yes, so the issue didn't seem to exist until I pulled. I have put in a work around on my end but it loses much of the error handling that could be done, but it does meet my needs.

Anyway, just wanted to give you a heads up in case you were about to put something into production. 

## 

Michael Dominick
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by owainhunt** [comment]
Crap. I'll take a look! Thanks for the prod.

**Comment by owainhunt** [comment]
Fixed in latest commit.
