### ISSUE TITLE
Build Error for iOS 5.1

### ISSUE THREAD

**Issue by jaischeema** [owainhunt/UAGithubEngine#25]
I tried using this in iOS project , it gave me three of these errors:

`Unexpected '@' in program`

This is happening due to the way your are constructing dictionaries

`@{ @"some_key" : @"some_value" }`

I just used `[NSDictionary dictionaryWithObjectsAndKeys:@"key", @"value", nil]` to make the errors go away.

I am new to iOS development, so might be doing something wrong.

**Comment by owainhunt** [comment]
The new @{} syntax is available for creating dictionaries as of Xcode 4.4. It does just the same as your replacement code but is less verbose.

**Comment by jaischeema** [comment]
Ohk, thats LLVM 4.0 feature. Thank you for prompt reply. :)
